# Generated by Django 4.1.4 on 2022-12-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.IntegerField(),
        ),
    ]
