# Generated by Django 4.1.4 on 2022-12-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_expense_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense',
            new_name='amount',
        ),
    ]
